[package]
name = "RustQuant"
description = "A Rust library for quantitative finance tools."
version = "0.1.0"
edition = "2021"
readme = "README.md"
keywords = [
    "finance",
    "quantitative",
    "option-pricing",
    "statistics",
    "quantlib",
]
categories = ["mathematics", "science", "algorithms", "simulation"]
license-file = "LICENSE"


[dependencies]
statrs = "0.16.0"
