[package]
name = "RustQuant"
description = "A Rust library for quantitative finance tools."
version = "0.0.16"
edition = "2021"
readme = "README.md"
repository = "https://github.com/avhz/RustQuant"
# documentation = "https://docs.rs/RustQuant"
keywords = [
    "finance",
    "quantitative",
    "option-pricing",
    "statistics",
    "quantlib",
]
categories = ["finance", "mathematics", "science", "algorithms", "simulation"]
license = "GPL-3.0-or-later"

[dependencies]
statrs = "0.16.0"
rand = "0.8.5"
rand_distr = "0.4.3"
plotters = "0.3.4"
rayon = "1.6.0"
num-complex = "0.4.2"
time = "0.3.20"
tempfile = "3.5.0"
csv = "1.2.1"
polars = { version = "0.29.0", features = [
    "serde",
    "json",
    "parquet",
    "ndarray",
    "dtype-struct",
    "dtype-date",
    "lazy",
] }
serde = "1.0.163"
yahoo_finance_api = "1.6.1"
tokio = "1.28.1"
tokio-test = "0.4.2"
serde_json = "1.0.96"
