## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## GENERAL CONFIGURATION
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[package]
name = "RustQuant"
description = "A Rust library for quantitative finance tools."
version = "0.0.19"
edition = "2021"
readme = "README.md"
repository = "https://github.com/avhz/RustQuant"
keywords = [
    "finance",
    "quantitative",
    "option-pricing",
    "statistics",
    "quantlib",
]
categories = ["finance", "mathematics", "science", "algorithms", "simulation"]
license = "GPL-3.0-or-later"

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## DEPENDENCIES
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[dependencies]
# csv = "1.2.1"             # https://docs.rs/csv/latest/csv/
nalgebra = "0.32.2"         # https://docs.rs/nalgebra/latest/nalgebra/
num-complex = "0.4.2"       # https://docs.rs/num-complex/latest/num_complex/
plotters = "0.3.4"          # https://docs.rs/plotters/latest/plotters/
rand = "0.8.5"              # https://docs.rs/rand/latest/rand/
rand_distr = "0.4.3"        # https://docs.rs/rand_distr/latest/rand_distr/
rayon = "1.6.0"             # https://docs.rs/rayon/latest/rayon/
serde = "1.0.163"           # https://docs.rs/serde/latest/serde/
serde_json = "1.0.96"       # https://docs.rs/serde_json/latest/serde_json/
statrs = "0.16.0"           # https://docs.rs/statrs/latest/statrs/
tempfile = "3.5.0"          # https://docs.rs/tempfile/latest/tempfile/
time = "0.3.20"             # https://docs.rs/time/latest/time/
tokio = "1.28.1"            # https://docs.rs/tokio/latest/tokio/
tokio-test = "0.4.2"        # https://docs.rs/tokio-test/latest/tokio_test/
yahoo_finance_api = "2.0.0" # https://docs.rs/yahoo-finance-api/latest/yahoo_finance_api/

[dependencies.polars] # https://docs.rs/polars/latest/polars/  
version = "0.30.0"
optional = true
features = ["serde", "json", "parquet", "dtype-struct", "dtype-date", "lazy"]

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## FEATURES
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[features]
## This feature is used to enable the use of the `data` module.
## It is disabled by default, since the addition of Polars
## increases the compilation time substantially.
data = ["dep:polars"]

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## EXAMPLES
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[example]]
name = "yahoo_finance"
required-features = ["data"]

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## PYTHON BINDINGS
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# [lib]
# name = "RustQuant"
# crate-type = ["cdylib"]

# [dependencies.pyo3]
# version = "0.19.0"
# features = ["abi3-py37", "extension-module"]
