## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## GENERAL CONFIGURATION
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[package]
name = "RustQuant"
authors = ["avhz <rustquantcontact@gmail.com>"]
description = "A Rust library for quantitative finance tools."
version = "0.0.23"
edition = "2021"
readme = "README.md"
repository = "https://github.com/avhz/RustQuant"
keywords = [
    "finance",
    "quantitative",
    "option-pricing",
    "statistics",
    "quantlib",
]
categories = ["finance", "mathematics", "science", "algorithms", "simulation"]
license = "GPL-3.0-or-later"

[profile.release]
debug = true


## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## DEPENDENCIES
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[dependencies]
# num = "0.4.0"               # https://docs.rs/num/latest/num/
# once_cell = "1.18.0"        # https://docs.rs/once_cell/latest/once_cell/
# csv = "1.1.6"               # https://docs.rs/csv/latest/csv/
# tempfile = "3.5.0"          # https://docs.rs/tempfile/latest/tempfile/
nalgebra = "0.32.2"         # https://docs.rs/nalgebra/latest/nalgebra/
ndarray = "0.15.6"          # https://docs.rs/ndarray/latest/ndarray/
num-complex = "0.4.2"       # https://docs.rs/num-complex/latest/num_complex/
plotters = "0.3.4"          # https://docs.rs/plotters/latest/plotters/
rand = "0.8.5"              # https://docs.rs/rand/latest/rand/
rand_distr = "0.4.3"        # https://docs.rs/rand_distr/latest/rand_distr/
rayon = "1.6.0"             # https://docs.rs/rayon/latest/rayon/
serde = "1.0.163"           # https://docs.rs/serde/latest/serde
serde_json = "1.0.96"       # https://docs.rs/serde_json/latest/serde_json
statrs = "0.16.0"           # https://docs.rs/statrs/latest/statrs/
time = "0.3.20"             # https://docs.rs/time/latest/time/
yahoo_finance_api = "2.0.0" # https://docs.rs/yahoo-finance-api/latest/yahoo_finance_api/

[dependencies.crossterm] # https://docs.rs/crossterm/latest/crossterm/
version = "0.26.1"
optional = true

[dependencies.eyre] # https://docs.rs/eyre/latest/eyre/
version = "0.6.8"
optional = true

[dependencies.log] # https://docs.rs/log/latest/log/
version = "0.4.19"
optional = true

[dependencies.polars] # https://docs.rs/polars/latest/polars/  
version = "0.30.0"
optional = true
features = ["serde", "json", "parquet", "dtype-struct", "dtype-date", "lazy"]

[dependencies.tokio] # https://docs.rs/tokio/latest/tokio/
version = "1.28.1"
optional = true
features = ["macros", "rt-multi-thread"]

[dependencies.tokio-test] # https://docs.rs/tokio-test/latest/tokio_test/
version = "0.4.2"
optional = true

[dependencies.tui] # https://docs.rs/tui/latest/tui/
version = "0.19.0"
optional = true

[dependencies.tui-logger] # https://docs.rs/tui-logger/latest/tui_logger/
version = "0.9.2"
optional = true


## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## FEATURES
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[features]
## This feature is used to enable the use of the `data` module.
## It is disabled by default, since the addition of Polars
## increases the compilation time substantially.
data = ["dep:polars", "dep:tokio", "dep:tokio-test"]
## This feature is used to enable the use of the `interactive` module.
interactive = [
    "dep:tui",
    "dep:tokio",
    "dep:tui-logger",
    "dep:crossterm",
    "dep:eyre",
    "dep:log",
]


## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## EXAMPLES
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[example]]
name = "yahoo_finance"
required-features = ["data"]


## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## TERMINAL USER INTERFACE
## This is simply a plan for the future.
##
## Run it: cargo run --features=interactive
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[bin]]
name = "RustQuant"
path = "src/interactive/main.rs"
required-features = ["interactive"]


## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## PYTHON BINDINGS
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# [lib]
# name = "RustQuant"
# crate-type = ["cdylib"]

# [dependencies.pyo3]
# version = "0.19.0"
# features = ["abi3-py37", "extension-module"]
